
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.magicstaffmod.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;

import net.minecraft.world.level.block.Block;

import net.mcreator.magicstaffmod.block.WaterOreBlock;
import net.mcreator.magicstaffmod.block.StoneOreBlock;
import net.mcreator.magicstaffmod.block.StoneManaOreBlock;
import net.mcreator.magicstaffmod.block.StoneIceOreBlock;
import net.mcreator.magicstaffmod.block.RuneWorldBeaconBlock;
import net.mcreator.magicstaffmod.block.RuneWoodBlock;
import net.mcreator.magicstaffmod.block.RuneTrapdoorBlock;
import net.mcreator.magicstaffmod.block.RuneStoneStairsBlock;
import net.mcreator.magicstaffmod.block.RuneStoneSlabBlock;
import net.mcreator.magicstaffmod.block.RuneStoneBrickBlock;
import net.mcreator.magicstaffmod.block.RuneStoneBlock;
import net.mcreator.magicstaffmod.block.RuneStairsBlock;
import net.mcreator.magicstaffmod.block.RuneSlabBlock;
import net.mcreator.magicstaffmod.block.RuneRedstoneOreBlock;
import net.mcreator.magicstaffmod.block.RunePlanksBlock;
import net.mcreator.magicstaffmod.block.RuneLogBlock;
import net.mcreator.magicstaffmod.block.RuneLeavesBlock;
import net.mcreator.magicstaffmod.block.RuneLapisLazuliOreBlock;
import net.mcreator.magicstaffmod.block.RuneIronOreBlock;
import net.mcreator.magicstaffmod.block.RuneHollowOreBlock;
import net.mcreator.magicstaffmod.block.RuneGoldOreBlock;
import net.mcreator.magicstaffmod.block.RuneFenceGateBlock;
import net.mcreator.magicstaffmod.block.RuneEmeraldOreBlock;
import net.mcreator.magicstaffmod.block.RuneDoorBlock;
import net.mcreator.magicstaffmod.block.RuneDiamondOreBlock;
import net.mcreator.magicstaffmod.block.RuneCopperOreBlock;
import net.mcreator.magicstaffmod.block.RuneCobblestoneBlock;
import net.mcreator.magicstaffmod.block.RuneCobbleWallBlock;
import net.mcreator.magicstaffmod.block.RuneCobbleStairsBlock;
import net.mcreator.magicstaffmod.block.RuneCobbleSlabBlock;
import net.mcreator.magicstaffmod.block.RuneBrickWallBlock;
import net.mcreator.magicstaffmod.block.RuneBrickStairsBlock;
import net.mcreator.magicstaffmod.block.RuneBrickSlabBlock;
import net.mcreator.magicstaffmod.block.ObsidianOreBlock;
import net.mcreator.magicstaffmod.block.ManaWoodBlock;
import net.mcreator.magicstaffmod.block.ManaTrapdoorBlock;
import net.mcreator.magicstaffmod.block.ManaStairsBlock;
import net.mcreator.magicstaffmod.block.ManaPlanksSlabBlock;
import net.mcreator.magicstaffmod.block.ManaPlanksBlock;
import net.mcreator.magicstaffmod.block.ManaLogBlock;
import net.mcreator.magicstaffmod.block.ManaLeavesBlock;
import net.mcreator.magicstaffmod.block.ManaFenceGateBlock;
import net.mcreator.magicstaffmod.block.ManaDoorBlock;
import net.mcreator.magicstaffmod.block.ManaBlockBlock;
import net.mcreator.magicstaffmod.block.IncompleteRuneWorldBeaconBlock;
import net.mcreator.magicstaffmod.block.HolySteelBlockBlock;
import net.mcreator.magicstaffmod.block.FireWoodBlock;
import net.mcreator.magicstaffmod.block.FireTrapdoorBlock;
import net.mcreator.magicstaffmod.block.FireStairsBlock;
import net.mcreator.magicstaffmod.block.FireSlabBlock;
import net.mcreator.magicstaffmod.block.FirePlanksBlock;
import net.mcreator.magicstaffmod.block.FireOreBlock;
import net.mcreator.magicstaffmod.block.FireLogBlock;
import net.mcreator.magicstaffmod.block.FireLeavesBlock;
import net.mcreator.magicstaffmod.block.FireFenceGateBlock;
import net.mcreator.magicstaffmod.block.FireDoorBlock;
import net.mcreator.magicstaffmod.block.EnderiteOreBlock;
import net.mcreator.magicstaffmod.block.DeepslateManaOreBlock;
import net.mcreator.magicstaffmod.block.DeepslateIceOreBlock;
import net.mcreator.magicstaffmod.block.CuttedRuneStoneBlock;
import net.mcreator.magicstaffmod.block.CorruptWoodBlock;
import net.mcreator.magicstaffmod.block.CorruptTrapdoorBlock;
import net.mcreator.magicstaffmod.block.CorruptStairsBlock;
import net.mcreator.magicstaffmod.block.CorruptSlabBlock;
import net.mcreator.magicstaffmod.block.CorruptPlanksBlock;
import net.mcreator.magicstaffmod.block.CorruptLogBlock;
import net.mcreator.magicstaffmod.block.CorruptLeavesBlock;
import net.mcreator.magicstaffmod.block.CorruptFenceGateBlock;
import net.mcreator.magicstaffmod.block.CorruptDoorBlock;
import net.mcreator.magicstaffmod.block.ActiveSoulSandBlock;
import net.mcreator.magicstaffmod.MaMod;

public class MaModBlocks {
	public static final DeferredRegister<Block> REGISTRY = DeferredRegister.create(ForgeRegistries.BLOCKS, MaMod.MODID);
	public static final RegistryObject<Block> STONE_MANA_ORE = REGISTRY.register("stone_mana_ore", () -> new StoneManaOreBlock());
	public static final RegistryObject<Block> DEEPSLATE_MANA_ORE = REGISTRY.register("deepslate_mana_ore", () -> new DeepslateManaOreBlock());
	public static final RegistryObject<Block> MANA_BLOCK = REGISTRY.register("mana_block", () -> new ManaBlockBlock());
	public static final RegistryObject<Block> WATER_ORE = REGISTRY.register("water_ore", () -> new WaterOreBlock());
	public static final RegistryObject<Block> FIRE_ORE = REGISTRY.register("fire_ore", () -> new FireOreBlock());
	public static final RegistryObject<Block> STONE_ORE = REGISTRY.register("stone_ore", () -> new StoneOreBlock());
	public static final RegistryObject<Block> OBSIDIAN_ORE = REGISTRY.register("obsidian_ore", () -> new ObsidianOreBlock());
	public static final RegistryObject<Block> STONE_ICE_ORE = REGISTRY.register("stone_ice_ore", () -> new StoneIceOreBlock());
	public static final RegistryObject<Block> DEEPSLATE_ICE_ORE = REGISTRY.register("deepslate_ice_ore", () -> new DeepslateIceOreBlock());
	public static final RegistryObject<Block> ACTIVE_SOUL_SAND = REGISTRY.register("active_soul_sand", () -> new ActiveSoulSandBlock());
	public static final RegistryObject<Block> HOLY_STEEL_BLOCK = REGISTRY.register("holy_steel_block", () -> new HolySteelBlockBlock());
	public static final RegistryObject<Block> ENDERITE_ORE = REGISTRY.register("enderite_ore", () -> new EnderiteOreBlock());
	public static final RegistryObject<Block> MANA_LOG = REGISTRY.register("mana_log", () -> new ManaLogBlock());
	public static final RegistryObject<Block> MANA_WOOD = REGISTRY.register("mana_wood", () -> new ManaWoodBlock());
	public static final RegistryObject<Block> MANA_PLANKS = REGISTRY.register("mana_planks", () -> new ManaPlanksBlock());
	public static final RegistryObject<Block> FIRE_LOG = REGISTRY.register("fire_log", () -> new FireLogBlock());
	public static final RegistryObject<Block> FIRE_WOOD = REGISTRY.register("fire_wood", () -> new FireWoodBlock());
	public static final RegistryObject<Block> FIRE_PLANKS = REGISTRY.register("fire_planks", () -> new FirePlanksBlock());
	public static final RegistryObject<Block> RUNE_LOG = REGISTRY.register("rune_log", () -> new RuneLogBlock());
	public static final RegistryObject<Block> RUNE_WOOD = REGISTRY.register("rune_wood", () -> new RuneWoodBlock());
	public static final RegistryObject<Block> RUNE_PLANKS = REGISTRY.register("rune_planks", () -> new RunePlanksBlock());
	public static final RegistryObject<Block> CORRUPT_LOG = REGISTRY.register("corrupt_log", () -> new CorruptLogBlock());
	public static final RegistryObject<Block> CORRUPT_WOOD = REGISTRY.register("corrupt_wood", () -> new CorruptWoodBlock());
	public static final RegistryObject<Block> CORRUPT_PLANKS = REGISTRY.register("corrupt_planks", () -> new CorruptPlanksBlock());
	public static final RegistryObject<Block> MANA_PLANKS_SLAB = REGISTRY.register("mana_planks_slab", () -> new ManaPlanksSlabBlock());
	public static final RegistryObject<Block> MANA_STAIRS = REGISTRY.register("mana_stairs", () -> new ManaStairsBlock());
	public static final RegistryObject<Block> FIRE_SLAB = REGISTRY.register("fire_slab", () -> new FireSlabBlock());
	public static final RegistryObject<Block> FIRE_STAIRS = REGISTRY.register("fire_stairs", () -> new FireStairsBlock());
	public static final RegistryObject<Block> RUNE_SLAB = REGISTRY.register("rune_slab", () -> new RuneSlabBlock());
	public static final RegistryObject<Block> RUNE_STAIRS = REGISTRY.register("rune_stairs", () -> new RuneStairsBlock());
	public static final RegistryObject<Block> CORRUPT_SLAB = REGISTRY.register("corrupt_slab", () -> new CorruptSlabBlock());
	public static final RegistryObject<Block> CORRUPT_STAIRS = REGISTRY.register("corrupt_stairs", () -> new CorruptStairsBlock());
	public static final RegistryObject<Block> RUNE_STONE = REGISTRY.register("rune_stone", () -> new RuneStoneBlock());
	public static final RegistryObject<Block> RUNE_STONE_STAIRS = REGISTRY.register("rune_stone_stairs", () -> new RuneStoneStairsBlock());
	public static final RegistryObject<Block> RUNE_STONE_SLAB = REGISTRY.register("rune_stone_slab", () -> new RuneStoneSlabBlock());
	public static final RegistryObject<Block> RUNE_COBBLESTONE = REGISTRY.register("rune_cobblestone", () -> new RuneCobblestoneBlock());
	public static final RegistryObject<Block> RUNE_COBBLE_STAIRS = REGISTRY.register("rune_cobble_stairs", () -> new RuneCobbleStairsBlock());
	public static final RegistryObject<Block> RUNE_COBBLE_SLAB = REGISTRY.register("rune_cobble_slab", () -> new RuneCobbleSlabBlock());
	public static final RegistryObject<Block> RUNE_STONE_BRICK = REGISTRY.register("rune_stone_brick", () -> new RuneStoneBrickBlock());
	public static final RegistryObject<Block> RUNE_BRICK_STAIRS = REGISTRY.register("rune_brick_stairs", () -> new RuneBrickStairsBlock());
	public static final RegistryObject<Block> RUNE_BRICK_SLAB = REGISTRY.register("rune_brick_slab", () -> new RuneBrickSlabBlock());
	public static final RegistryObject<Block> CUTTED_RUNE_STONE = REGISTRY.register("cutted_rune_stone", () -> new CuttedRuneStoneBlock());
	public static final RegistryObject<Block> RUNE_COBBLE_WALL = REGISTRY.register("rune_cobble_wall", () -> new RuneCobbleWallBlock());
	public static final RegistryObject<Block> RUNE_BRICK_WALL = REGISTRY.register("rune_brick_wall", () -> new RuneBrickWallBlock());
	public static final RegistryObject<Block> RUNE_LAPIS_LAZULI_ORE = REGISTRY.register("rune_lapis_lazuli_ore", () -> new RuneLapisLazuliOreBlock());
	public static final RegistryObject<Block> RUNE_REDSTONE_ORE = REGISTRY.register("rune_redstone_ore", () -> new RuneRedstoneOreBlock());
	public static final RegistryObject<Block> RUNE_IRON_ORE = REGISTRY.register("rune_iron_ore", () -> new RuneIronOreBlock());
	public static final RegistryObject<Block> RUNE_GOLD_ORE = REGISTRY.register("rune_gold_ore", () -> new RuneGoldOreBlock());
	public static final RegistryObject<Block> RUNE_DIAMOND_ORE = REGISTRY.register("rune_diamond_ore", () -> new RuneDiamondOreBlock());
	public static final RegistryObject<Block> RUNE_EMERALD_ORE = REGISTRY.register("rune_emerald_ore", () -> new RuneEmeraldOreBlock());
	public static final RegistryObject<Block> RUNE_COPPER_ORE = REGISTRY.register("rune_copper_ore", () -> new RuneCopperOreBlock());
	public static final RegistryObject<Block> RUNE_HOLLOW_ORE = REGISTRY.register("rune_hollow_ore", () -> new RuneHollowOreBlock());
	public static final RegistryObject<Block> MANA_LEAVES = REGISTRY.register("mana_leaves", () -> new ManaLeavesBlock());
	public static final RegistryObject<Block> FIRE_LEAVES = REGISTRY.register("fire_leaves", () -> new FireLeavesBlock());
	public static final RegistryObject<Block> RUNE_LEAVES = REGISTRY.register("rune_leaves", () -> new RuneLeavesBlock());
	public static final RegistryObject<Block> CORRUPT_LEAVES = REGISTRY.register("corrupt_leaves", () -> new CorruptLeavesBlock());
	public static final RegistryObject<Block> INCOMPLETE_RUNE_WORLD_BEACON = REGISTRY.register("incomplete_rune_world_beacon",
			() -> new IncompleteRuneWorldBeaconBlock());
	public static final RegistryObject<Block> RUNE_WORLD_BEACON = REGISTRY.register("rune_world_beacon", () -> new RuneWorldBeaconBlock());
	public static final RegistryObject<Block> MANA_DOOR = REGISTRY.register("mana_door", () -> new ManaDoorBlock());
	public static final RegistryObject<Block> RUNE_DOOR = REGISTRY.register("rune_door", () -> new RuneDoorBlock());
	public static final RegistryObject<Block> FIRE_DOOR = REGISTRY.register("fire_door", () -> new FireDoorBlock());
	public static final RegistryObject<Block> CORRUPT_DOOR = REGISTRY.register("corrupt_door", () -> new CorruptDoorBlock());
	public static final RegistryObject<Block> MANA_TRAPDOOR = REGISTRY.register("mana_trapdoor", () -> new ManaTrapdoorBlock());
	public static final RegistryObject<Block> RUNE_TRAPDOOR = REGISTRY.register("rune_trapdoor", () -> new RuneTrapdoorBlock());
	public static final RegistryObject<Block> FIRE_TRAPDOOR = REGISTRY.register("fire_trapdoor", () -> new FireTrapdoorBlock());
	public static final RegistryObject<Block> CORRUPT_TRAPDOOR = REGISTRY.register("corrupt_trapdoor", () -> new CorruptTrapdoorBlock());
	public static final RegistryObject<Block> MANA_FENCE_GATE = REGISTRY.register("mana_fence_gate", () -> new ManaFenceGateBlock());
	public static final RegistryObject<Block> RUNE_FENCE_GATE = REGISTRY.register("rune_fence_gate", () -> new RuneFenceGateBlock());
	public static final RegistryObject<Block> FIRE_FENCE_GATE = REGISTRY.register("fire_fence_gate", () -> new FireFenceGateBlock());
	public static final RegistryObject<Block> CORRUPT_FENCE_GATE = REGISTRY.register("corrupt_fence_gate", () -> new CorruptFenceGateBlock());
}
